name: Production

on:
    push:
        branches:
            - main

jobs:
    call-deploy:
        name: Deploy to prod
        uses: ./.github/workflows/build-deploy.yml
        with:
            environment: frontierconsolidated.com
            hostname: frontierconsolidated.com
            frontend_service: frcn-prod-frontend.service
            backend_service: frcn-prod-backend.service
        secrets:
            SSH_USER: ${{ secrets.SSH_USER }}
            SSH_KEY: ${{ secrets.SSH_KEY }}
            SSH_HOST: ${{ secrets.SSH_HOST }}
            SSH_PORT: ${{ secrets.SSH_PORT }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}
            AWS_SECURITY_GROUP: ${{ secrets.AWS_SECURITY_GROUP }}
