name: Docs CI
on:
    pull_request:
        branches:
            - main
            - dev
        paths:
            - docs/**

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  submodules: true
                  # If using the 'assets' git submodule from Chirpy Starter, uncomment above
                  # (See: https://github.com/cotes2020/chirpy-starter/tree/main/assets)

            - name: Setup Ruby
              uses: ruby/setup-ruby@v1
              with:
                  ruby-version: 3.2
                  bundler-cache: true

            - name: Install dependencies
              run: cd docs && bundle install

            - name: Build site
              run: cd docs && bundle exec jekyll b -d "_site$BASE_PATH"
              env:
                  BASE_PATH: "/frcn-web"
                  JEKYLL_ENV: "production"

            - name: Test site
              run: |
                  cd docs && bundle exec htmlproofer _site \
                    \-\-disable-external=true \
                    \-\-ignore-urls "/^http:\/\/127.0.0.1/,/^http:\/\/0.0.0.0/,/^http:\/\/localhost/"
